language: ruby

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1
  - jruby-9.2

jdk:
- oraclejdk8

cache: bundler

bundler_args: --without development

after_success: bundle exec codeclimate-test-reporter
